// SEO Constants for Navigator
export const SITE_CONFIG = {
  name: "Navigator",
  company: "Navigator Technologies 1802",
  tagline: "Group Travel Made Simple",
  description: "Plan group trips effortlessly with Navigator. Split expenses, coordinate flights, chat, and vote on plans — all in one place.",
  domain: "navigatortrips.com",
  url: "https://navigatortrips.com",
  email: "info@navigatortrips.com",
  ogImage: "https://navigatortrips.com/og-image.png",
  logo: "https://navigatortrips.com/assets/ab_Navigator2-11_1749673259080.png",
} as const;

export const SEO_PAGES = {
  home: {
    title: "Navigator — Group Travel Planner | Plan Trips with Friends | Navigator 1802",
    description: "Navigator is the best group travel planner for planning trips with friends. Plan group trips, split expenses, coordinate flights, and chat — all in one place. Navigator 1802 makes travel planning simple.",
    keywords: "navigator, group travel, travel planner, trips, navigator 1802, plan trips with friends, group travel planner, navigator trips, navigatortrip, navigator app, group travel app, trip planning app, travel organizer, collaborative travel planner",
    path: "/",
  },
  about: {
    title: "About — Navigator Technologies 1802",
    description: "Learn about Navigator Technologies 1802, the team building seamless tools to simplify group travel and coordination.",
    keywords: "about Navigator, travel technology",
    path: "/about",
  },
  contact: {
    title: "Contact — Navigator",
    description: "Get in touch with Navigator Technologies 1802. We're here to help you simplify your next group adventure.",
    keywords: "contact Navigator, support",
    path: "/contact",
  },
  terms: {
    title: "Terms of Service — Navigator",
    description: "Read the terms and conditions for using Navigator's group travel tools and services.",
    keywords: "terms of service, Navigator",
    path: "/terms",
  },
  privacy: {
    title: "Privacy Policy — Navigator",
    description: "Learn how Navigator Technologies 1802 handles your data responsibly and transparently.",
    keywords: "privacy policy, data security",
    path: "/privacy",
  },
  legal: {
    title: "Legal — Navigator Technologies 1802",
    description: "Legal information and compliance resources for Navigator Technologies 1802.",
    keywords: "legal, compliance",
    path: "/legal",
  },
} as const;

// Primary keywords for the site (prioritized by user's target keywords)
export const PRIMARY_KEYWORDS = [
  // User's Priority Keywords
  "navigator",
  "group travel",
  "travel planner",
  "trips",
  "navigator 1802",
  "plan trips with friends",
  "group travel planner",
  "navigator trips",
  "navigatortrip",
  // Additional high-value keywords
  "navigator app",
  "navigator travel",
  "navigator group planner",
  "navigator journeys",
  "navigator technologies",
  "navigator beta",
  "trip planner",
  "group travel app",
  "group itinerary",
  "travel organizer",
  "trip planning app",
  "itinerary builder",
  "travel planning tool",
  "group trip planning",
  "travel planning app",
  "collaborative travel",
  "travel itinerary app",
  "travel schedule maker",
  "vacation planner",
  "friends trip",
  "group trips with friends",
  "travel with friends",
  "travel chat",
  "shared itinerary",
  "trip messaging",
  "travel group chat",
  "plan trip together",
  "collaborative trip planner",
  "travel community app",
  "split expenses",
  "group expenses",
  "travel expenses",
  "trip budgeting",
  "expense sharing app",
  "settle up",
  "split payments",
  "payback tracker",
  "travel budget app",
  "group budget manager",
  "venmo trip planner",
  "paypal expense split",
  "rsvp trips",
  "trip invites",
  "invite friends",
  "travel poll",
  "group decision app",
  "trip notifications",
  "itinerary updates",
  "travel reminders",
  "activity planning",
  "trip tasks",
  "flight search",
  "airport status",
  "trip alerts",
  "adventure planner",
  "road trip planner",
  "travel memories",
  "backpacking planner",
  "travel stories",
  "travel inspiration",
  "wanderlust app",
  "spontaneous trips",
  "weekend getaway planner",
  "travel diary",
  "nostalgic travel",
  "freedom to travel",
  "shared moments",
  "modern travel app",
  "effortless planning",
  "no more awkward splits",
  "remember the moments",
  "explore together",
  "navigator trips app",
  "travel app beta",
  "group travel organizer",
  "mobile travel planner",
  "trip planning startup",
  "best group trip app",
  "free travel planner",
  "travel startup",
  "ai travel planner",
  "social trip app",
  "1802",
];

